### ISSUE TITLE
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (Connection: mysql, SQL: alter table `users` add unique `users_email_unique`(`email`))

### ISSUE THREAD

**Issue by ForsanNemah** [ferdiunal/filament-crm#1]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (Connection: mysql, SQL: alter table `users` add unique `users_email_unique`(`email`))

**Comment by ferdiunal** [comment]
This error is not related to filament-crm, I suggest you do some research.
[https://stackoverflow.com/a/42245921](https://stackoverflow.com/a/42245921)
[https://stackoverflow.com/a/46641266](https://stackoverflow.com/a/46641266)
